/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { DEXDrainer__factory } from "./DEXDrainer__factory";
export { IOSLODEXDrain__factory } from "./IOSLODEXDrain__factory";
