/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IInvestmentEngine,
  IInvestmentEngineInterface,
} from "../../../contracts/interfaces/IInvestmentEngine";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
    ],
    name: "getActiveDeposit",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
    ],
    name: "getUserTier",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "notifyLevelIncome",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "notifyRankBonus",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IInvestmentEngine__factory {
  static readonly abi = _abi;
  static createInterface(): IInvestmentEngineInterface {
    return new Interface(_abi) as IInvestmentEngineInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IInvestmentEngine {
    return new Contract(address, _abi, runner) as unknown as IInvestmentEngine;
  }
}
