/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IOSLODEX,
  IOSLODEXInterface,
} from "../../../contracts/interfaces/IOSLODEX";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "usdtAmount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "osloAmount",
        type: "uint256",
      },
    ],
    name: "addInitialLiquidity",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "usdtAmount",
        type: "uint256",
      },
    ],
    name: "addLiquidityFromFees",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "osloAmount",
        type: "uint256",
      },
    ],
    name: "getOSLOForUSDTOutput",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getPrice",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getReserves",
    outputs: [
      {
        internalType: "uint256",
        name: "usdtRes",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "osloRes",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "usdtAmount",
        type: "uint256",
      },
    ],
    name: "getUSDTForOSLOOutput",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "usdtAmount",
        type: "uint256",
      },
    ],
    name: "processDeposit",
    outputs: [
      {
        internalType: "uint256",
        name: "osloAmount",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "osloAmount",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "recipient",
        type: "address",
      },
    ],
    name: "processWithdrawal",
    outputs: [
      {
        internalType: "uint256",
        name: "usdtAmount",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "osloAmount",
        type: "uint256",
      },
    ],
    name: "replenishOsloReserve",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "osloAmount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "minUSDTAmount",
        type: "uint256",
      },
    ],
    name: "swapOSLOForUSDT",
    outputs: [
      {
        internalType: "uint256",
        name: "usdtAmount",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "usdtAmount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "minOsloAmount",
        type: "uint256",
      },
    ],
    name: "swapUSDTForOSLO",
    outputs: [
      {
        internalType: "uint256",
        name: "osloAmount",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IOSLODEX__factory {
  static readonly abi = _abi;
  static createInterface(): IOSLODEXInterface {
    return new Interface(_abi) as IOSLODEXInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IOSLODEX {
    return new Contract(address, _abi, runner) as unknown as IOSLODEX;
  }
}
