/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface OSLODAOInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "admin"
      | "checkAndQualify"
      | "claimRoyalty"
      | "completeSetup"
      | "configure"
      | "daoMemberCount"
      | "daoMembers"
      | "genesisTimestamp"
      | "getAllDAOMembers"
      | "getCurrentMonthId"
      | "getPendingRoyalty"
      | "investmentEngine"
      | "isDAOMember"
      | "monthlyTurnover"
      | "receiveRoyaltyPool"
      | "recordMonthlyTurnover"
      | "royaltyClaimed"
      | "royaltyPoolBalance"
      | "setupComplete"
      | "timelock"
      | "totalRoyaltiesDistributed"
      | "usdt"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DAOMemberQualified"
      | "MonthlyTurnoverRecorded"
      | "RoyaltyClaimed"
      | "RoyaltyPoolFunded"
  ): EventFragment;

  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "checkAndQualify",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimRoyalty",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "completeSetup",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "configure",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "daoMemberCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "daoMembers",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "genesisTimestamp",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAllDAOMembers",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentMonthId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPendingRoyalty",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "investmentEngine",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isDAOMember",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "monthlyTurnover",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "receiveRoyaltyPool",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "recordMonthlyTurnover",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "royaltyClaimed",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "royaltyPoolBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setupComplete",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "timelock", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "totalRoyaltiesDistributed",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "usdt", values?: undefined): string;

  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "checkAndQualify",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimRoyalty",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "completeSetup",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "configure", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "daoMemberCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "daoMembers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "genesisTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllDAOMembers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentMonthId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPendingRoyalty",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "investmentEngine",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isDAOMember",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "monthlyTurnover",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "receiveRoyaltyPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordMonthlyTurnover",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "royaltyClaimed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "royaltyPoolBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setupComplete",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "timelock", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalRoyaltiesDistributed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdt", data: BytesLike): Result;
}

export namespace DAOMemberQualifiedEvent {
  export type InputTuple = [
    user: AddressLike,
    memberNumber: BigNumberish,
    teamSize: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    memberNumber: bigint,
    teamSize: bigint
  ];
  export interface OutputObject {
    user: string;
    memberNumber: bigint;
    teamSize: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MonthlyTurnoverRecordedEvent {
  export type InputTuple = [monthId: BigNumberish, amount: BigNumberish];
  export type OutputTuple = [monthId: bigint, amount: bigint];
  export interface OutputObject {
    monthId: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoyaltyClaimedEvent {
  export type InputTuple = [
    user: AddressLike,
    amount: BigNumberish,
    monthId: BigNumberish
  ];
  export type OutputTuple = [user: string, amount: bigint, monthId: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
    monthId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoyaltyPoolFundedEvent {
  export type InputTuple = [amount: BigNumberish];
  export type OutputTuple = [amount: bigint];
  export interface OutputObject {
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface OSLODAO extends BaseContract {
  connect(runner?: ContractRunner | null): OSLODAO;
  waitForDeployment(): Promise<this>;

  interface: OSLODAOInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  admin: TypedContractMethod<[], [string], "view">;

  checkAndQualify: TypedContractMethod<
    [user: AddressLike, teamSize: BigNumberish],
    [void],
    "nonpayable"
  >;

  claimRoyalty: TypedContractMethod<[], [void], "nonpayable">;

  completeSetup: TypedContractMethod<[], [void], "nonpayable">;

  configure: TypedContractMethod<
    [_timelock: AddressLike, _investmentEngine: AddressLike],
    [void],
    "nonpayable"
  >;

  daoMemberCount: TypedContractMethod<[], [bigint], "view">;

  daoMembers: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  genesisTimestamp: TypedContractMethod<[], [bigint], "view">;

  getAllDAOMembers: TypedContractMethod<[], [string[]], "view">;

  getCurrentMonthId: TypedContractMethod<[], [bigint], "view">;

  getPendingRoyalty: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  investmentEngine: TypedContractMethod<[], [string], "view">;

  isDAOMember: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  monthlyTurnover: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  receiveRoyaltyPool: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  recordMonthlyTurnover: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  royaltyClaimed: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [boolean],
    "view"
  >;

  royaltyPoolBalance: TypedContractMethod<[], [bigint], "view">;

  setupComplete: TypedContractMethod<[], [boolean], "view">;

  timelock: TypedContractMethod<[], [string], "view">;

  totalRoyaltiesDistributed: TypedContractMethod<[], [bigint], "view">;

  usdt: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "checkAndQualify"
  ): TypedContractMethod<
    [user: AddressLike, teamSize: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "claimRoyalty"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "completeSetup"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "configure"
  ): TypedContractMethod<
    [_timelock: AddressLike, _investmentEngine: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "daoMemberCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "daoMembers"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "genesisTimestamp"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getAllDAOMembers"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getCurrentMonthId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPendingRoyalty"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "investmentEngine"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "isDAOMember"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "monthlyTurnover"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "receiveRoyaltyPool"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "recordMonthlyTurnover"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "royaltyClaimed"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "royaltyPoolBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "setupComplete"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "timelock"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "totalRoyaltiesDistributed"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "usdt"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "DAOMemberQualified"
  ): TypedContractEvent<
    DAOMemberQualifiedEvent.InputTuple,
    DAOMemberQualifiedEvent.OutputTuple,
    DAOMemberQualifiedEvent.OutputObject
  >;
  getEvent(
    key: "MonthlyTurnoverRecorded"
  ): TypedContractEvent<
    MonthlyTurnoverRecordedEvent.InputTuple,
    MonthlyTurnoverRecordedEvent.OutputTuple,
    MonthlyTurnoverRecordedEvent.OutputObject
  >;
  getEvent(
    key: "RoyaltyClaimed"
  ): TypedContractEvent<
    RoyaltyClaimedEvent.InputTuple,
    RoyaltyClaimedEvent.OutputTuple,
    RoyaltyClaimedEvent.OutputObject
  >;
  getEvent(
    key: "RoyaltyPoolFunded"
  ): TypedContractEvent<
    RoyaltyPoolFundedEvent.InputTuple,
    RoyaltyPoolFundedEvent.OutputTuple,
    RoyaltyPoolFundedEvent.OutputObject
  >;

  filters: {
    "DAOMemberQualified(address,uint256,uint256)": TypedContractEvent<
      DAOMemberQualifiedEvent.InputTuple,
      DAOMemberQualifiedEvent.OutputTuple,
      DAOMemberQualifiedEvent.OutputObject
    >;
    DAOMemberQualified: TypedContractEvent<
      DAOMemberQualifiedEvent.InputTuple,
      DAOMemberQualifiedEvent.OutputTuple,
      DAOMemberQualifiedEvent.OutputObject
    >;

    "MonthlyTurnoverRecorded(uint256,uint256)": TypedContractEvent<
      MonthlyTurnoverRecordedEvent.InputTuple,
      MonthlyTurnoverRecordedEvent.OutputTuple,
      MonthlyTurnoverRecordedEvent.OutputObject
    >;
    MonthlyTurnoverRecorded: TypedContractEvent<
      MonthlyTurnoverRecordedEvent.InputTuple,
      MonthlyTurnoverRecordedEvent.OutputTuple,
      MonthlyTurnoverRecordedEvent.OutputObject
    >;

    "RoyaltyClaimed(address,uint256,uint256)": TypedContractEvent<
      RoyaltyClaimedEvent.InputTuple,
      RoyaltyClaimedEvent.OutputTuple,
      RoyaltyClaimedEvent.OutputObject
    >;
    RoyaltyClaimed: TypedContractEvent<
      RoyaltyClaimedEvent.InputTuple,
      RoyaltyClaimedEvent.OutputTuple,
      RoyaltyClaimedEvent.OutputObject
    >;

    "RoyaltyPoolFunded(uint256)": TypedContractEvent<
      RoyaltyPoolFundedEvent.InputTuple,
      RoyaltyPoolFundedEvent.OutputTuple,
      RoyaltyPoolFundedEvent.OutputObject
    >;
    RoyaltyPoolFunded: TypedContractEvent<
      RoyaltyPoolFundedEvent.InputTuple,
      RoyaltyPoolFundedEvent.OutputTuple,
      RoyaltyPoolFundedEvent.OutputObject
    >;
  };
}
