/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface OSLOReferralInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "REGISTRATION_FEE"
      | "admin"
      | "checkAndUnlockLevels"
      | "claimReferralRewards"
      | "completeSetup"
      | "configure"
      | "distributeReferralCommission"
      | "getAllLevelIncome"
      | "getDirectReferrals"
      | "getLevelIncome"
      | "getQualifiedDirectsCount"
      | "getReferrer"
      | "getTeamSize"
      | "getUnlockedLevels"
      | "investmentEngine"
      | "isRegistered"
      | "levelIncome"
      | "migrateUsers"
      | "osloDex"
      | "osloToken"
      | "referralRewards"
      | "register"
      | "setInvestmentEngine"
      | "setupComplete"
      | "timelock"
      | "totalCommissionsPaid"
      | "totalFeesCollected"
      | "totalRegistered"
      | "usdt"
      | "userInfo"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "LevelUnlocked"
      | "ReferralPaid"
      | "ReferralRewardsClaimed"
      | "RegistrationFeeProcessed"
      | "UserRegistered"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "REGISTRATION_FEE",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "checkAndUnlockLevels",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claimReferralRewards",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "completeSetup",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "configure",
    values: [AddressLike, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "distributeReferralCommission",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllLevelIncome",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getDirectReferrals",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getLevelIncome",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getQualifiedDirectsCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getReferrer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTeamSize",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUnlockedLevels",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "investmentEngine",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isRegistered",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "levelIncome",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "migrateUsers",
    values: [AddressLike[], AddressLike[], BigNumberish[]]
  ): string;
  encodeFunctionData(functionFragment: "osloDex", values?: undefined): string;
  encodeFunctionData(functionFragment: "osloToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "referralRewards",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "register",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setInvestmentEngine",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setupComplete",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "timelock", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "totalCommissionsPaid",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalFeesCollected",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalRegistered",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "usdt", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "userInfo",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "REGISTRATION_FEE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "checkAndUnlockLevels",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimReferralRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "completeSetup",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "configure", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "distributeReferralCommission",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllLevelIncome",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDirectReferrals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLevelIncome",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getQualifiedDirectsCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReferrer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTeamSize",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUnlockedLevels",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "investmentEngine",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isRegistered",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "levelIncome",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "migrateUsers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "osloDex", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "osloToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "referralRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "register", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setInvestmentEngine",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setupComplete",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "timelock", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalCommissionsPaid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalFeesCollected",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalRegistered",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdt", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "userInfo", data: BytesLike): Result;
}

export namespace LevelUnlockedEvent {
  export type InputTuple = [user: AddressLike, level: BigNumberish];
  export type OutputTuple = [user: string, level: bigint];
  export interface OutputObject {
    user: string;
    level: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReferralPaidEvent {
  export type InputTuple = [
    upline: AddressLike,
    downline: AddressLike,
    level: BigNumberish,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    upline: string,
    downline: string,
    level: bigint,
    amount: bigint
  ];
  export interface OutputObject {
    upline: string;
    downline: string;
    level: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReferralRewardsClaimedEvent {
  export type InputTuple = [user: AddressLike, amount: BigNumberish];
  export type OutputTuple = [user: string, amount: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RegistrationFeeProcessedEvent {
  export type InputTuple = [
    user: AddressLike,
    fee: BigNumberish,
    osloBurned: BigNumberish
  ];
  export type OutputTuple = [user: string, fee: bigint, osloBurned: bigint];
  export interface OutputObject {
    user: string;
    fee: bigint;
    osloBurned: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UserRegisteredEvent {
  export type InputTuple = [user: AddressLike, referrer: AddressLike];
  export type OutputTuple = [user: string, referrer: string];
  export interface OutputObject {
    user: string;
    referrer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface OSLOReferral extends BaseContract {
  connect(runner?: ContractRunner | null): OSLOReferral;
  waitForDeployment(): Promise<this>;

  interface: OSLOReferralInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  REGISTRATION_FEE: TypedContractMethod<[], [bigint], "view">;

  admin: TypedContractMethod<[], [string], "view">;

  checkAndUnlockLevels: TypedContractMethod<
    [user: AddressLike],
    [void],
    "nonpayable"
  >;

  claimReferralRewards: TypedContractMethod<[], [void], "nonpayable">;

  completeSetup: TypedContractMethod<[], [void], "nonpayable">;

  configure: TypedContractMethod<
    [
      _investmentEngine: AddressLike,
      _osloDex: AddressLike,
      _timelock: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  distributeReferralCommission: TypedContractMethod<
    [user: AddressLike, profitAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getAllLevelIncome: TypedContractMethod<
    [user: AddressLike],
    [bigint[]],
    "view"
  >;

  getDirectReferrals: TypedContractMethod<
    [user: AddressLike],
    [string[]],
    "view"
  >;

  getLevelIncome: TypedContractMethod<
    [user: AddressLike, level: BigNumberish],
    [bigint],
    "view"
  >;

  getQualifiedDirectsCount: TypedContractMethod<
    [user: AddressLike],
    [bigint],
    "view"
  >;

  getReferrer: TypedContractMethod<[user: AddressLike], [string], "view">;

  getTeamSize: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  getUnlockedLevels: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  investmentEngine: TypedContractMethod<[], [string], "view">;

  isRegistered: TypedContractMethod<[user: AddressLike], [boolean], "view">;

  levelIncome: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  migrateUsers: TypedContractMethod<
    [
      _users: AddressLike[],
      _referrers: AddressLike[],
      _unlockedLevels: BigNumberish[]
    ],
    [void],
    "nonpayable"
  >;

  osloDex: TypedContractMethod<[], [string], "view">;

  osloToken: TypedContractMethod<[], [string], "view">;

  referralRewards: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  register: TypedContractMethod<
    [user: AddressLike, referrer: AddressLike],
    [void],
    "nonpayable"
  >;

  setInvestmentEngine: TypedContractMethod<
    [_investmentEngine: AddressLike],
    [void],
    "nonpayable"
  >;

  setupComplete: TypedContractMethod<[], [boolean], "view">;

  timelock: TypedContractMethod<[], [string], "view">;

  totalCommissionsPaid: TypedContractMethod<[], [bigint], "view">;

  totalFeesCollected: TypedContractMethod<[], [bigint], "view">;

  totalRegistered: TypedContractMethod<[], [bigint], "view">;

  usdt: TypedContractMethod<[], [string], "view">;

  userInfo: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, bigint, bigint, boolean] & {
        referrer: string;
        unlockedLevels: bigint;
        totalEarned: bigint;
        registered: boolean;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "REGISTRATION_FEE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "checkAndUnlockLevels"
  ): TypedContractMethod<[user: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimReferralRewards"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "completeSetup"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "configure"
  ): TypedContractMethod<
    [
      _investmentEngine: AddressLike,
      _osloDex: AddressLike,
      _timelock: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "distributeReferralCommission"
  ): TypedContractMethod<
    [user: AddressLike, profitAmount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAllLevelIncome"
  ): TypedContractMethod<[user: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getDirectReferrals"
  ): TypedContractMethod<[user: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getLevelIncome"
  ): TypedContractMethod<
    [user: AddressLike, level: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getQualifiedDirectsCount"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getReferrer"
  ): TypedContractMethod<[user: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getTeamSize"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUnlockedLevels"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "investmentEngine"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "isRegistered"
  ): TypedContractMethod<[user: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "levelIncome"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "migrateUsers"
  ): TypedContractMethod<
    [
      _users: AddressLike[],
      _referrers: AddressLike[],
      _unlockedLevels: BigNumberish[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "osloDex"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "osloToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "referralRewards"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "register"
  ): TypedContractMethod<
    [user: AddressLike, referrer: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setInvestmentEngine"
  ): TypedContractMethod<
    [_investmentEngine: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setupComplete"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "timelock"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "totalCommissionsPaid"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalFeesCollected"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalRegistered"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "usdt"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "userInfo"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, bigint, bigint, boolean] & {
        referrer: string;
        unlockedLevels: bigint;
        totalEarned: bigint;
        registered: boolean;
      }
    ],
    "view"
  >;

  getEvent(
    key: "LevelUnlocked"
  ): TypedContractEvent<
    LevelUnlockedEvent.InputTuple,
    LevelUnlockedEvent.OutputTuple,
    LevelUnlockedEvent.OutputObject
  >;
  getEvent(
    key: "ReferralPaid"
  ): TypedContractEvent<
    ReferralPaidEvent.InputTuple,
    ReferralPaidEvent.OutputTuple,
    ReferralPaidEvent.OutputObject
  >;
  getEvent(
    key: "ReferralRewardsClaimed"
  ): TypedContractEvent<
    ReferralRewardsClaimedEvent.InputTuple,
    ReferralRewardsClaimedEvent.OutputTuple,
    ReferralRewardsClaimedEvent.OutputObject
  >;
  getEvent(
    key: "RegistrationFeeProcessed"
  ): TypedContractEvent<
    RegistrationFeeProcessedEvent.InputTuple,
    RegistrationFeeProcessedEvent.OutputTuple,
    RegistrationFeeProcessedEvent.OutputObject
  >;
  getEvent(
    key: "UserRegistered"
  ): TypedContractEvent<
    UserRegisteredEvent.InputTuple,
    UserRegisteredEvent.OutputTuple,
    UserRegisteredEvent.OutputObject
  >;

  filters: {
    "LevelUnlocked(address,uint256)": TypedContractEvent<
      LevelUnlockedEvent.InputTuple,
      LevelUnlockedEvent.OutputTuple,
      LevelUnlockedEvent.OutputObject
    >;
    LevelUnlocked: TypedContractEvent<
      LevelUnlockedEvent.InputTuple,
      LevelUnlockedEvent.OutputTuple,
      LevelUnlockedEvent.OutputObject
    >;

    "ReferralPaid(address,address,uint256,uint256)": TypedContractEvent<
      ReferralPaidEvent.InputTuple,
      ReferralPaidEvent.OutputTuple,
      ReferralPaidEvent.OutputObject
    >;
    ReferralPaid: TypedContractEvent<
      ReferralPaidEvent.InputTuple,
      ReferralPaidEvent.OutputTuple,
      ReferralPaidEvent.OutputObject
    >;

    "ReferralRewardsClaimed(address,uint256)": TypedContractEvent<
      ReferralRewardsClaimedEvent.InputTuple,
      ReferralRewardsClaimedEvent.OutputTuple,
      ReferralRewardsClaimedEvent.OutputObject
    >;
    ReferralRewardsClaimed: TypedContractEvent<
      ReferralRewardsClaimedEvent.InputTuple,
      ReferralRewardsClaimedEvent.OutputTuple,
      ReferralRewardsClaimedEvent.OutputObject
    >;

    "RegistrationFeeProcessed(address,uint256,uint256)": TypedContractEvent<
      RegistrationFeeProcessedEvent.InputTuple,
      RegistrationFeeProcessedEvent.OutputTuple,
      RegistrationFeeProcessedEvent.OutputObject
    >;
    RegistrationFeeProcessed: TypedContractEvent<
      RegistrationFeeProcessedEvent.InputTuple,
      RegistrationFeeProcessedEvent.OutputTuple,
      RegistrationFeeProcessedEvent.OutputObject
    >;

    "UserRegistered(address,address)": TypedContractEvent<
      UserRegisteredEvent.InputTuple,
      UserRegisteredEvent.OutputTuple,
      UserRegisteredEvent.OutputObject
    >;
    UserRegistered: TypedContractEvent<
      UserRegisteredEvent.InputTuple,
      UserRegisteredEvent.OutputTuple,
      UserRegisteredEvent.OutputObject
    >;
  };
}
