/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace OSLOVault {
  export type PoolMigrationStruct = {
    owner: AddressLike;
    totalBalance: BigNumberish;
    lastClaimTime: BigNumberish;
    totalClaimed: BigNumberish;
    totalCombinedEarnings: BigNumberish;
    lastDepositTime: BigNumberish;
  };

  export type PoolMigrationStructOutput = [
    owner: string,
    totalBalance: bigint,
    lastClaimTime: bigint,
    totalClaimed: bigint,
    totalCombinedEarnings: bigint,
    lastDepositTime: bigint
  ] & {
    owner: string;
    totalBalance: bigint;
    lastClaimTime: bigint;
    totalClaimed: bigint;
    totalCombinedEarnings: bigint;
    lastDepositTime: bigint;
  };
}

export interface OSLOVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "admin"
      | "claimRewards"
      | "companyWallet"
      | "completeSetup"
      | "configure"
      | "deposit"
      | "depositsPaused"
      | "getActiveDeposit"
      | "getCombinedEarnings"
      | "getPendingRewards"
      | "getUserPool"
      | "getUserTier"
      | "launchTimestamp"
      | "migrateCombinedEarnings"
      | "migrateConsolidated"
      | "minClaimThreshold"
      | "notifyLevelIncome"
      | "notifyRankBonus"
      | "osloDex"
      | "osloToken"
      | "performanceWallet"
      | "rankSystem"
      | "referral"
      | "rewardWallet"
      | "setDepositsPaused"
      | "setMinClaimThreshold"
      | "setReferral"
      | "setRewardWallets"
      | "setupComplete"
      | "timelock"
      | "totalDeposited"
      | "totalRewardsPaid"
      | "totalWithdrawn"
      | "usdt"
      | "userPools"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CombinedCapReached"
      | "CombinedEarningsUpdated"
      | "Deposited"
      | "DepositsPaused"
      | "RewardsClaimed"
  ): EventFragment;

  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "claimRewards",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "companyWallet",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "completeSetup",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "configure",
    values: [AddressLike, AddressLike, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "depositsPaused",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getActiveDeposit",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getCombinedEarnings",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPendingRewards",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserPool",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserTier",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "launchTimestamp",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "migrateCombinedEarnings",
    values: [AddressLike[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "migrateConsolidated",
    values: [OSLOVault.PoolMigrationStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "minClaimThreshold",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "notifyLevelIncome",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "notifyRankBonus",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "osloDex", values?: undefined): string;
  encodeFunctionData(functionFragment: "osloToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "performanceWallet",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rankSystem",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "referral", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "rewardWallet",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setDepositsPaused",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setMinClaimThreshold",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setReferral",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setRewardWallets",
    values: [AddressLike, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setupComplete",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "timelock", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "totalDeposited",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalRewardsPaid",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalWithdrawn",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "usdt", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "userPools",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "claimRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "companyWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "completeSetup",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "configure", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "depositsPaused",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getActiveDeposit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCombinedEarnings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPendingRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserTier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "launchTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "migrateCombinedEarnings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "migrateConsolidated",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minClaimThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "notifyLevelIncome",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "notifyRankBonus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "osloDex", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "osloToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "performanceWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "rankSystem", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "referral", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "rewardWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDepositsPaused",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMinClaimThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setReferral",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRewardWallets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setupComplete",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "timelock", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalDeposited",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalRewardsPaid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalWithdrawn",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdt", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "userPools", data: BytesLike): Result;
}

export namespace CombinedCapReachedEvent {
  export type InputTuple = [user: AddressLike];
  export type OutputTuple = [user: string];
  export interface OutputObject {
    user: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CombinedEarningsUpdatedEvent {
  export type InputTuple = [user: AddressLike, totalCombined: BigNumberish];
  export type OutputTuple = [user: string, totalCombined: bigint];
  export interface OutputObject {
    user: string;
    totalCombined: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositedEvent {
  export type InputTuple = [
    user: AddressLike,
    amount: BigNumberish,
    newTotal: BigNumberish,
    tier: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    amount: bigint,
    newTotal: bigint,
    tier: bigint
  ];
  export interface OutputObject {
    user: string;
    amount: bigint;
    newTotal: bigint;
    tier: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositsPausedEvent {
  export type InputTuple = [paused: boolean];
  export type OutputTuple = [paused: boolean];
  export interface OutputObject {
    paused: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardsClaimedEvent {
  export type InputTuple = [
    user: AddressLike,
    usdtReward: BigNumberish,
    osloAmount: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    usdtReward: bigint,
    osloAmount: bigint
  ];
  export interface OutputObject {
    user: string;
    usdtReward: bigint;
    osloAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface OSLOVault extends BaseContract {
  connect(runner?: ContractRunner | null): OSLOVault;
  waitForDeployment(): Promise<this>;

  interface: OSLOVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  admin: TypedContractMethod<[], [string], "view">;

  claimRewards: TypedContractMethod<[], [void], "nonpayable">;

  companyWallet: TypedContractMethod<[], [string], "view">;

  completeSetup: TypedContractMethod<[], [void], "nonpayable">;

  configure: TypedContractMethod<
    [
      _osloDex: AddressLike,
      _referral: AddressLike,
      _rankSystem: AddressLike,
      _timelock: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  deposit: TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  depositsPaused: TypedContractMethod<[], [boolean], "view">;

  getActiveDeposit: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  getCombinedEarnings: TypedContractMethod<
    [user: AddressLike],
    [bigint],
    "view"
  >;

  getPendingRewards: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  getUserPool: TypedContractMethod<
    [user: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint, bigint, boolean] & {
        totalBalance: bigint;
        lastClaimTime: bigint;
        accruedRewards: bigint;
        totalClaimed: bigint;
        maxReturn: bigint;
        totalCombinedEarnings: bigint;
        lastDepositTime: bigint;
        active: boolean;
      }
    ],
    "view"
  >;

  getUserTier: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  launchTimestamp: TypedContractMethod<[], [bigint], "view">;

  migrateCombinedEarnings: TypedContractMethod<
    [_users: AddressLike[], _amounts: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  migrateConsolidated: TypedContractMethod<
    [entries: OSLOVault.PoolMigrationStruct[]],
    [void],
    "nonpayable"
  >;

  minClaimThreshold: TypedContractMethod<[], [bigint], "view">;

  notifyLevelIncome: TypedContractMethod<
    [user: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  notifyRankBonus: TypedContractMethod<
    [user: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  osloDex: TypedContractMethod<[], [string], "view">;

  osloToken: TypedContractMethod<[], [string], "view">;

  performanceWallet: TypedContractMethod<[], [string], "view">;

  rankSystem: TypedContractMethod<[], [string], "view">;

  referral: TypedContractMethod<[], [string], "view">;

  rewardWallet: TypedContractMethod<[], [string], "view">;

  setDepositsPaused: TypedContractMethod<
    [_paused: boolean],
    [void],
    "nonpayable"
  >;

  setMinClaimThreshold: TypedContractMethod<
    [_threshold: BigNumberish],
    [void],
    "nonpayable"
  >;

  setReferral: TypedContractMethod<
    [_referral: AddressLike],
    [void],
    "nonpayable"
  >;

  setRewardWallets: TypedContractMethod<
    [
      _rewardWallet: AddressLike,
      _companyWallet: AddressLike,
      _performanceWallet: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  setupComplete: TypedContractMethod<[], [boolean], "view">;

  timelock: TypedContractMethod<[], [string], "view">;

  totalDeposited: TypedContractMethod<[], [bigint], "view">;

  totalRewardsPaid: TypedContractMethod<[], [bigint], "view">;

  totalWithdrawn: TypedContractMethod<[], [bigint], "view">;

  usdt: TypedContractMethod<[], [string], "view">;

  userPools: TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint, bigint, boolean] & {
        totalBalance: bigint;
        lastClaimTime: bigint;
        accruedRewards: bigint;
        totalClaimed: bigint;
        maxReturn: bigint;
        totalCombinedEarnings: bigint;
        lastDepositTime: bigint;
        active: boolean;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "claimRewards"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "companyWallet"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "completeSetup"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "configure"
  ): TypedContractMethod<
    [
      _osloDex: AddressLike,
      _referral: AddressLike,
      _rankSystem: AddressLike,
      _timelock: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "depositsPaused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "getActiveDeposit"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getCombinedEarnings"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPendingRewards"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserPool"
  ): TypedContractMethod<
    [user: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint, bigint, boolean] & {
        totalBalance: bigint;
        lastClaimTime: bigint;
        accruedRewards: bigint;
        totalClaimed: bigint;
        maxReturn: bigint;
        totalCombinedEarnings: bigint;
        lastDepositTime: bigint;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserTier"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "launchTimestamp"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "migrateCombinedEarnings"
  ): TypedContractMethod<
    [_users: AddressLike[], _amounts: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "migrateConsolidated"
  ): TypedContractMethod<
    [entries: OSLOVault.PoolMigrationStruct[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "minClaimThreshold"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "notifyLevelIncome"
  ): TypedContractMethod<
    [user: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "notifyRankBonus"
  ): TypedContractMethod<
    [user: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "osloDex"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "osloToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "performanceWallet"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "rankSystem"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "referral"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "rewardWallet"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setDepositsPaused"
  ): TypedContractMethod<[_paused: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMinClaimThreshold"
  ): TypedContractMethod<[_threshold: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setReferral"
  ): TypedContractMethod<[_referral: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setRewardWallets"
  ): TypedContractMethod<
    [
      _rewardWallet: AddressLike,
      _companyWallet: AddressLike,
      _performanceWallet: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setupComplete"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "timelock"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "totalDeposited"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalRewardsPaid"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalWithdrawn"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "usdt"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "userPools"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint, bigint, boolean] & {
        totalBalance: bigint;
        lastClaimTime: bigint;
        accruedRewards: bigint;
        totalClaimed: bigint;
        maxReturn: bigint;
        totalCombinedEarnings: bigint;
        lastDepositTime: bigint;
        active: boolean;
      }
    ],
    "view"
  >;

  getEvent(
    key: "CombinedCapReached"
  ): TypedContractEvent<
    CombinedCapReachedEvent.InputTuple,
    CombinedCapReachedEvent.OutputTuple,
    CombinedCapReachedEvent.OutputObject
  >;
  getEvent(
    key: "CombinedEarningsUpdated"
  ): TypedContractEvent<
    CombinedEarningsUpdatedEvent.InputTuple,
    CombinedEarningsUpdatedEvent.OutputTuple,
    CombinedEarningsUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Deposited"
  ): TypedContractEvent<
    DepositedEvent.InputTuple,
    DepositedEvent.OutputTuple,
    DepositedEvent.OutputObject
  >;
  getEvent(
    key: "DepositsPaused"
  ): TypedContractEvent<
    DepositsPausedEvent.InputTuple,
    DepositsPausedEvent.OutputTuple,
    DepositsPausedEvent.OutputObject
  >;
  getEvent(
    key: "RewardsClaimed"
  ): TypedContractEvent<
    RewardsClaimedEvent.InputTuple,
    RewardsClaimedEvent.OutputTuple,
    RewardsClaimedEvent.OutputObject
  >;

  filters: {
    "CombinedCapReached(address)": TypedContractEvent<
      CombinedCapReachedEvent.InputTuple,
      CombinedCapReachedEvent.OutputTuple,
      CombinedCapReachedEvent.OutputObject
    >;
    CombinedCapReached: TypedContractEvent<
      CombinedCapReachedEvent.InputTuple,
      CombinedCapReachedEvent.OutputTuple,
      CombinedCapReachedEvent.OutputObject
    >;

    "CombinedEarningsUpdated(address,uint256)": TypedContractEvent<
      CombinedEarningsUpdatedEvent.InputTuple,
      CombinedEarningsUpdatedEvent.OutputTuple,
      CombinedEarningsUpdatedEvent.OutputObject
    >;
    CombinedEarningsUpdated: TypedContractEvent<
      CombinedEarningsUpdatedEvent.InputTuple,
      CombinedEarningsUpdatedEvent.OutputTuple,
      CombinedEarningsUpdatedEvent.OutputObject
    >;

    "Deposited(address,uint256,uint256,uint256)": TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;
    Deposited: TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;

    "DepositsPaused(bool)": TypedContractEvent<
      DepositsPausedEvent.InputTuple,
      DepositsPausedEvent.OutputTuple,
      DepositsPausedEvent.OutputObject
    >;
    DepositsPaused: TypedContractEvent<
      DepositsPausedEvent.InputTuple,
      DepositsPausedEvent.OutputTuple,
      DepositsPausedEvent.OutputObject
    >;

    "RewardsClaimed(address,uint256,uint256)": TypedContractEvent<
      RewardsClaimedEvent.InputTuple,
      RewardsClaimedEvent.OutputTuple,
      RewardsClaimedEvent.OutputObject
    >;
    RewardsClaimed: TypedContractEvent<
      RewardsClaimedEvent.InputTuple,
      RewardsClaimedEvent.OutputTuple,
      RewardsClaimedEvent.OutputObject
    >;
  };
}
