/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface OSLODEXInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addInitialLiquidity"
      | "addLiquidityFromFees"
      | "admin"
      | "completeSetup"
      | "configure"
      | "drainUSDT"
      | "forceSetInvestmentEngine"
      | "forceSetReferralContract"
      | "getOSLOForUSDTOutput"
      | "getPrice"
      | "getReserves"
      | "getUSDTForOSLOOutput"
      | "injectUSDTLiquidity"
      | "investmentEngine"
      | "lastPrice"
      | "liquidityManager"
      | "osloReserve"
      | "osloToken"
      | "processDeposit"
      | "processWithdrawal"
      | "referralContract"
      | "replenishOsloReserve"
      | "setInvestmentEngine"
      | "setReferralContract"
      | "setupComplete"
      | "swapOSLOForUSDT"
      | "swapUSDTForOSLO"
      | "swapYieldForOSLO"
      | "timelock"
      | "totalSwaps"
      | "totalVolumeUSDT"
      | "usdt"
      | "usdtReserve"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DepositProcessed"
      | "LiquidityDeposited"
      | "PriceUpdated"
      | "Swapped"
      | "WithdrawalProcessed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addInitialLiquidity",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "addLiquidityFromFees",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "completeSetup",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "configure",
    values: [AddressLike, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "drainUSDT",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "forceSetInvestmentEngine",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "forceSetReferralContract",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getOSLOForUSDTOutput",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "getPrice", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getReserves",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUSDTForOSLOOutput",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "injectUSDTLiquidity",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "investmentEngine",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "lastPrice", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "liquidityManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "osloReserve",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "osloToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "processDeposit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "processWithdrawal",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "referralContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "replenishOsloReserve",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setInvestmentEngine",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setReferralContract",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setupComplete",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "swapOSLOForUSDT",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "swapUSDTForOSLO",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "swapYieldForOSLO",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "timelock", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "totalSwaps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalVolumeUSDT",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "usdt", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "usdtReserve",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "addInitialLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addLiquidityFromFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "completeSetup",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "configure", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "drainUSDT", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "forceSetInvestmentEngine",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "forceSetReferralContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOSLOForUSDTOutput",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPrice", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getReserves",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUSDTForOSLOOutput",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "injectUSDTLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "investmentEngine",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "lastPrice", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "liquidityManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "osloReserve",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "osloToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "processDeposit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "processWithdrawal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "referralContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "replenishOsloReserve",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setInvestmentEngine",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setReferralContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setupComplete",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapOSLOForUSDT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapUSDTForOSLO",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapYieldForOSLO",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "timelock", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "totalSwaps", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalVolumeUSDT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdt", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "usdtReserve",
    data: BytesLike
  ): Result;
}

export namespace DepositProcessedEvent {
  export type InputTuple = [usdtIn: BigNumberish, osloOut: BigNumberish];
  export type OutputTuple = [usdtIn: bigint, osloOut: bigint];
  export interface OutputObject {
    usdtIn: bigint;
    osloOut: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LiquidityDepositedEvent {
  export type InputTuple = [usdtAmount: BigNumberish, osloAmount: BigNumberish];
  export type OutputTuple = [usdtAmount: bigint, osloAmount: bigint];
  export interface OutputObject {
    usdtAmount: bigint;
    osloAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PriceUpdatedEvent {
  export type InputTuple = [newPrice: BigNumberish];
  export type OutputTuple = [newPrice: bigint];
  export interface OutputObject {
    newPrice: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SwappedEvent {
  export type InputTuple = [
    user: AddressLike,
    usdtToOslo: boolean,
    inputAmount: BigNumberish,
    outputAmount: BigNumberish,
    price: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    usdtToOslo: boolean,
    inputAmount: bigint,
    outputAmount: bigint,
    price: bigint
  ];
  export interface OutputObject {
    user: string;
    usdtToOslo: boolean;
    inputAmount: bigint;
    outputAmount: bigint;
    price: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawalProcessedEvent {
  export type InputTuple = [
    osloIn: BigNumberish,
    usdtOut: BigNumberish,
    recipient: AddressLike
  ];
  export type OutputTuple = [
    osloIn: bigint,
    usdtOut: bigint,
    recipient: string
  ];
  export interface OutputObject {
    osloIn: bigint;
    usdtOut: bigint;
    recipient: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface OSLODEX extends BaseContract {
  connect(runner?: ContractRunner | null): OSLODEX;
  waitForDeployment(): Promise<this>;

  interface: OSLODEXInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addInitialLiquidity: TypedContractMethod<
    [usdtAmount: BigNumberish, osloAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  addLiquidityFromFees: TypedContractMethod<
    [usdtAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  admin: TypedContractMethod<[], [string], "view">;

  completeSetup: TypedContractMethod<[], [void], "nonpayable">;

  configure: TypedContractMethod<
    [
      _timelock: AddressLike,
      _liquidityManager: AddressLike,
      _investmentEngine: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  drainUSDT: TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  forceSetInvestmentEngine: TypedContractMethod<
    [_investmentEngine: AddressLike],
    [void],
    "nonpayable"
  >;

  forceSetReferralContract: TypedContractMethod<
    [_referralContract: AddressLike],
    [void],
    "nonpayable"
  >;

  getOSLOForUSDTOutput: TypedContractMethod<
    [osloAmount: BigNumberish],
    [bigint],
    "view"
  >;

  getPrice: TypedContractMethod<[], [bigint], "view">;

  getReserves: TypedContractMethod<
    [],
    [[bigint, bigint] & { _usdtRes: bigint; _osloRes: bigint }],
    "view"
  >;

  getUSDTForOSLOOutput: TypedContractMethod<
    [usdtAmount: BigNumberish],
    [bigint],
    "view"
  >;

  injectUSDTLiquidity: TypedContractMethod<
    [usdtAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  investmentEngine: TypedContractMethod<[], [string], "view">;

  lastPrice: TypedContractMethod<[], [bigint], "view">;

  liquidityManager: TypedContractMethod<[], [string], "view">;

  osloReserve: TypedContractMethod<[], [bigint], "view">;

  osloToken: TypedContractMethod<[], [string], "view">;

  processDeposit: TypedContractMethod<
    [usdtAmount: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  processWithdrawal: TypedContractMethod<
    [osloAmount: BigNumberish, recipient: AddressLike],
    [bigint],
    "nonpayable"
  >;

  referralContract: TypedContractMethod<[], [string], "view">;

  replenishOsloReserve: TypedContractMethod<
    [osloAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  setInvestmentEngine: TypedContractMethod<
    [_investmentEngine: AddressLike],
    [void],
    "nonpayable"
  >;

  setReferralContract: TypedContractMethod<
    [_referralContract: AddressLike],
    [void],
    "nonpayable"
  >;

  setupComplete: TypedContractMethod<[], [boolean], "view">;

  swapOSLOForUSDT: TypedContractMethod<
    [osloAmount: BigNumberish, minUSDTAmount: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  swapUSDTForOSLO: TypedContractMethod<
    [usdtAmount: BigNumberish, minOsloAmount: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  swapYieldForOSLO: TypedContractMethod<
    [usdtAmount: BigNumberish, recipient: AddressLike],
    [bigint],
    "nonpayable"
  >;

  timelock: TypedContractMethod<[], [string], "view">;

  totalSwaps: TypedContractMethod<[], [bigint], "view">;

  totalVolumeUSDT: TypedContractMethod<[], [bigint], "view">;

  usdt: TypedContractMethod<[], [string], "view">;

  usdtReserve: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addInitialLiquidity"
  ): TypedContractMethod<
    [usdtAmount: BigNumberish, osloAmount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addLiquidityFromFees"
  ): TypedContractMethod<[usdtAmount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "completeSetup"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "configure"
  ): TypedContractMethod<
    [
      _timelock: AddressLike,
      _liquidityManager: AddressLike,
      _investmentEngine: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "drainUSDT"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "forceSetInvestmentEngine"
  ): TypedContractMethod<
    [_investmentEngine: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "forceSetReferralContract"
  ): TypedContractMethod<
    [_referralContract: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getOSLOForUSDTOutput"
  ): TypedContractMethod<[osloAmount: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPrice"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getReserves"
  ): TypedContractMethod<
    [],
    [[bigint, bigint] & { _usdtRes: bigint; _osloRes: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUSDTForOSLOOutput"
  ): TypedContractMethod<[usdtAmount: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "injectUSDTLiquidity"
  ): TypedContractMethod<[usdtAmount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "investmentEngine"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "lastPrice"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "liquidityManager"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "osloReserve"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "osloToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "processDeposit"
  ): TypedContractMethod<[usdtAmount: BigNumberish], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "processWithdrawal"
  ): TypedContractMethod<
    [osloAmount: BigNumberish, recipient: AddressLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "referralContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "replenishOsloReserve"
  ): TypedContractMethod<[osloAmount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setInvestmentEngine"
  ): TypedContractMethod<
    [_investmentEngine: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setReferralContract"
  ): TypedContractMethod<
    [_referralContract: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setupComplete"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "swapOSLOForUSDT"
  ): TypedContractMethod<
    [osloAmount: BigNumberish, minUSDTAmount: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "swapUSDTForOSLO"
  ): TypedContractMethod<
    [usdtAmount: BigNumberish, minOsloAmount: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "swapYieldForOSLO"
  ): TypedContractMethod<
    [usdtAmount: BigNumberish, recipient: AddressLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "timelock"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "totalSwaps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalVolumeUSDT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "usdt"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "usdtReserve"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "DepositProcessed"
  ): TypedContractEvent<
    DepositProcessedEvent.InputTuple,
    DepositProcessedEvent.OutputTuple,
    DepositProcessedEvent.OutputObject
  >;
  getEvent(
    key: "LiquidityDeposited"
  ): TypedContractEvent<
    LiquidityDepositedEvent.InputTuple,
    LiquidityDepositedEvent.OutputTuple,
    LiquidityDepositedEvent.OutputObject
  >;
  getEvent(
    key: "PriceUpdated"
  ): TypedContractEvent<
    PriceUpdatedEvent.InputTuple,
    PriceUpdatedEvent.OutputTuple,
    PriceUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Swapped"
  ): TypedContractEvent<
    SwappedEvent.InputTuple,
    SwappedEvent.OutputTuple,
    SwappedEvent.OutputObject
  >;
  getEvent(
    key: "WithdrawalProcessed"
  ): TypedContractEvent<
    WithdrawalProcessedEvent.InputTuple,
    WithdrawalProcessedEvent.OutputTuple,
    WithdrawalProcessedEvent.OutputObject
  >;

  filters: {
    "DepositProcessed(uint256,uint256)": TypedContractEvent<
      DepositProcessedEvent.InputTuple,
      DepositProcessedEvent.OutputTuple,
      DepositProcessedEvent.OutputObject
    >;
    DepositProcessed: TypedContractEvent<
      DepositProcessedEvent.InputTuple,
      DepositProcessedEvent.OutputTuple,
      DepositProcessedEvent.OutputObject
    >;

    "LiquidityDeposited(uint256,uint256)": TypedContractEvent<
      LiquidityDepositedEvent.InputTuple,
      LiquidityDepositedEvent.OutputTuple,
      LiquidityDepositedEvent.OutputObject
    >;
    LiquidityDeposited: TypedContractEvent<
      LiquidityDepositedEvent.InputTuple,
      LiquidityDepositedEvent.OutputTuple,
      LiquidityDepositedEvent.OutputObject
    >;

    "PriceUpdated(uint256)": TypedContractEvent<
      PriceUpdatedEvent.InputTuple,
      PriceUpdatedEvent.OutputTuple,
      PriceUpdatedEvent.OutputObject
    >;
    PriceUpdated: TypedContractEvent<
      PriceUpdatedEvent.InputTuple,
      PriceUpdatedEvent.OutputTuple,
      PriceUpdatedEvent.OutputObject
    >;

    "Swapped(address,bool,uint256,uint256,uint256)": TypedContractEvent<
      SwappedEvent.InputTuple,
      SwappedEvent.OutputTuple,
      SwappedEvent.OutputObject
    >;
    Swapped: TypedContractEvent<
      SwappedEvent.InputTuple,
      SwappedEvent.OutputTuple,
      SwappedEvent.OutputObject
    >;

    "WithdrawalProcessed(uint256,uint256,address)": TypedContractEvent<
      WithdrawalProcessedEvent.InputTuple,
      WithdrawalProcessedEvent.OutputTuple,
      WithdrawalProcessedEvent.OutputObject
    >;
    WithdrawalProcessed: TypedContractEvent<
      WithdrawalProcessedEvent.InputTuple,
      WithdrawalProcessedEvent.OutputTuple,
      WithdrawalProcessedEvent.OutputObject
    >;
  };
}
