/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface OSLOLiquidityManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addInitialLiquidity"
      | "addLiquidityFromFees"
      | "admin"
      | "completeSetup"
      | "configure"
      | "getDEXReserves"
      | "getOSLOPrice"
      | "osloToken"
      | "oslodex"
      | "rescueERC20"
      | "setupComplete"
      | "timelock"
      | "totalLiquidityAdded"
      | "usdt"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "LiquidityAdded" | "TokensRescued"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addInitialLiquidity",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "addLiquidityFromFees",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "completeSetup",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "configure",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getDEXReserves",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getOSLOPrice",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "osloToken", values?: undefined): string;
  encodeFunctionData(functionFragment: "oslodex", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "rescueERC20",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setupComplete",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "timelock", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "totalLiquidityAdded",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "usdt", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "addInitialLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addLiquidityFromFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "completeSetup",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "configure", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getDEXReserves",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOSLOPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "osloToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "oslodex", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "rescueERC20",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setupComplete",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "timelock", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalLiquidityAdded",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdt", data: BytesLike): Result;
}

export namespace LiquidityAddedEvent {
  export type InputTuple = [usdtAmount: BigNumberish, osloAmount: BigNumberish];
  export type OutputTuple = [usdtAmount: bigint, osloAmount: bigint];
  export interface OutputObject {
    usdtAmount: bigint;
    osloAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokensRescuedEvent {
  export type InputTuple = [token: AddressLike, amount: BigNumberish];
  export type OutputTuple = [token: string, amount: bigint];
  export interface OutputObject {
    token: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface OSLOLiquidityManager extends BaseContract {
  connect(runner?: ContractRunner | null): OSLOLiquidityManager;
  waitForDeployment(): Promise<this>;

  interface: OSLOLiquidityManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addInitialLiquidity: TypedContractMethod<
    [usdtAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  addLiquidityFromFees: TypedContractMethod<
    [usdtAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  admin: TypedContractMethod<[], [string], "view">;

  completeSetup: TypedContractMethod<[], [void], "nonpayable">;

  configure: TypedContractMethod<
    [_timelock: AddressLike, _oslodex: AddressLike],
    [void],
    "nonpayable"
  >;

  getDEXReserves: TypedContractMethod<
    [],
    [[bigint, bigint] & { _usdtRes: bigint; _osloRes: bigint }],
    "view"
  >;

  getOSLOPrice: TypedContractMethod<[], [bigint], "view">;

  osloToken: TypedContractMethod<[], [string], "view">;

  oslodex: TypedContractMethod<[], [string], "view">;

  rescueERC20: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  setupComplete: TypedContractMethod<[], [boolean], "view">;

  timelock: TypedContractMethod<[], [string], "view">;

  totalLiquidityAdded: TypedContractMethod<[], [bigint], "view">;

  usdt: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addInitialLiquidity"
  ): TypedContractMethod<[usdtAmount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "addLiquidityFromFees"
  ): TypedContractMethod<[usdtAmount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "completeSetup"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "configure"
  ): TypedContractMethod<
    [_timelock: AddressLike, _oslodex: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getDEXReserves"
  ): TypedContractMethod<
    [],
    [[bigint, bigint] & { _usdtRes: bigint; _osloRes: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getOSLOPrice"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "osloToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "oslodex"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "rescueERC20"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setupComplete"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "timelock"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "totalLiquidityAdded"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "usdt"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "LiquidityAdded"
  ): TypedContractEvent<
    LiquidityAddedEvent.InputTuple,
    LiquidityAddedEvent.OutputTuple,
    LiquidityAddedEvent.OutputObject
  >;
  getEvent(
    key: "TokensRescued"
  ): TypedContractEvent<
    TokensRescuedEvent.InputTuple,
    TokensRescuedEvent.OutputTuple,
    TokensRescuedEvent.OutputObject
  >;

  filters: {
    "LiquidityAdded(uint256,uint256)": TypedContractEvent<
      LiquidityAddedEvent.InputTuple,
      LiquidityAddedEvent.OutputTuple,
      LiquidityAddedEvent.OutputObject
    >;
    LiquidityAdded: TypedContractEvent<
      LiquidityAddedEvent.InputTuple,
      LiquidityAddedEvent.OutputTuple,
      LiquidityAddedEvent.OutputObject
    >;

    "TokensRescued(address,uint256)": TypedContractEvent<
      TokensRescuedEvent.InputTuple,
      TokensRescuedEvent.OutputTuple,
      TokensRescuedEvent.OutputObject
    >;
    TokensRescued: TypedContractEvent<
      TokensRescuedEvent.InputTuple,
      TokensRescuedEvent.OutputTuple,
      TokensRescuedEvent.OutputObject
    >;
  };
}
