/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface DEXDrainerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "dex"
      | "drainOSLO"
      | "drainUSDT"
      | "osloToken"
      | "owner"
      | "rescue"
      | "rescueBNB"
      | "usdt"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "dex", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "drainOSLO",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "drainUSDT",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "osloToken", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "rescue", values: [AddressLike]): string;
  encodeFunctionData(functionFragment: "rescueBNB", values?: undefined): string;
  encodeFunctionData(functionFragment: "usdt", values?: undefined): string;

  decodeFunctionResult(functionFragment: "dex", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "drainOSLO", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "drainUSDT", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "osloToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "rescue", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "rescueBNB", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "usdt", data: BytesLike): Result;
}

export interface DEXDrainer extends BaseContract {
  connect(runner?: ContractRunner | null): DEXDrainer;
  waitForDeployment(): Promise<this>;

  interface: DEXDrainerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  dex: TypedContractMethod<[], [string], "view">;

  drainOSLO: TypedContractMethod<
    [usdtAmount: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  drainUSDT: TypedContractMethod<
    [osloAmount: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  osloToken: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  rescue: TypedContractMethod<[token: AddressLike], [void], "nonpayable">;

  rescueBNB: TypedContractMethod<[], [void], "nonpayable">;

  usdt: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "dex"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "drainOSLO"
  ): TypedContractMethod<[usdtAmount: BigNumberish], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "drainUSDT"
  ): TypedContractMethod<[osloAmount: BigNumberish], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "osloToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "rescue"
  ): TypedContractMethod<[token: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "rescueBNB"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "usdt"
  ): TypedContractMethod<[], [string], "view">;

  filters: {};
}
