/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IOSLODEXDrainInterface extends Interface {
  getFunction(
    nameOrSignature: "getReserves" | "processWithdrawal" | "swapYieldForOSLO"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getReserves",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "processWithdrawal",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "swapYieldForOSLO",
    values: [BigNumberish, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "getReserves",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "processWithdrawal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapYieldForOSLO",
    data: BytesLike
  ): Result;
}

export interface IOSLODEXDrain extends BaseContract {
  connect(runner?: ContractRunner | null): IOSLODEXDrain;
  waitForDeployment(): Promise<this>;

  interface: IOSLODEXDrainInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getReserves: TypedContractMethod<
    [],
    [[bigint, bigint] & { usdtRes: bigint; osloRes: bigint }],
    "view"
  >;

  processWithdrawal: TypedContractMethod<
    [osloAmount: BigNumberish, recipient: AddressLike],
    [bigint],
    "nonpayable"
  >;

  swapYieldForOSLO: TypedContractMethod<
    [usdtAmount: BigNumberish, recipient: AddressLike],
    [bigint],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getReserves"
  ): TypedContractMethod<
    [],
    [[bigint, bigint] & { usdtRes: bigint; osloRes: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "processWithdrawal"
  ): TypedContractMethod<
    [osloAmount: BigNumberish, recipient: AddressLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "swapYieldForOSLO"
  ): TypedContractMethod<
    [usdtAmount: BigNumberish, recipient: AddressLike],
    [bigint],
    "nonpayable"
  >;

  filters: {};
}
