/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IOSLODexV2Interface extends Interface {
  getFunction(
    nameOrSignature:
      | "addInitialLiquidity"
      | "getOSLOForUSDT"
      | "getPrice"
      | "getReserves"
      | "getUSDTForOSLO"
      | "injectUSDTLiquidity"
      | "processBuy"
      | "processWithdrawal"
      | "replenishOsloReserve"
      | "sellOSLO"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addInitialLiquidity",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getOSLOForUSDT",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "getPrice", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getReserves",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUSDTForOSLO",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "injectUSDTLiquidity",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "processBuy",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "processWithdrawal",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "replenishOsloReserve",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "sellOSLO",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "addInitialLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOSLOForUSDT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPrice", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getReserves",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUSDTForOSLO",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "injectUSDTLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "processBuy", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "processWithdrawal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "replenishOsloReserve",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "sellOSLO", data: BytesLike): Result;
}

export interface IOSLODexV2 extends BaseContract {
  connect(runner?: ContractRunner | null): IOSLODexV2;
  waitForDeployment(): Promise<this>;

  interface: IOSLODexV2Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addInitialLiquidity: TypedContractMethod<
    [usdtAmount: BigNumberish, osloAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getOSLOForUSDT: TypedContractMethod<
    [usdtAmount: BigNumberish],
    [bigint],
    "view"
  >;

  getPrice: TypedContractMethod<[], [bigint], "view">;

  getReserves: TypedContractMethod<
    [],
    [[bigint, bigint] & { usdtReserve: bigint; osloReserve: bigint }],
    "view"
  >;

  getUSDTForOSLO: TypedContractMethod<
    [osloAmount: BigNumberish],
    [bigint],
    "view"
  >;

  injectUSDTLiquidity: TypedContractMethod<
    [usdtAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  processBuy: TypedContractMethod<
    [usdtAmount: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  processWithdrawal: TypedContractMethod<
    [osloAmount: BigNumberish, recipient: AddressLike],
    [bigint],
    "nonpayable"
  >;

  replenishOsloReserve: TypedContractMethod<
    [osloAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  sellOSLO: TypedContractMethod<
    [osloAmount: BigNumberish, minUSDTOut: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addInitialLiquidity"
  ): TypedContractMethod<
    [usdtAmount: BigNumberish, osloAmount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getOSLOForUSDT"
  ): TypedContractMethod<[usdtAmount: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPrice"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getReserves"
  ): TypedContractMethod<
    [],
    [[bigint, bigint] & { usdtReserve: bigint; osloReserve: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUSDTForOSLO"
  ): TypedContractMethod<[osloAmount: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "injectUSDTLiquidity"
  ): TypedContractMethod<[usdtAmount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "processBuy"
  ): TypedContractMethod<[usdtAmount: BigNumberish], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "processWithdrawal"
  ): TypedContractMethod<
    [osloAmount: BigNumberish, recipient: AddressLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "replenishOsloReserve"
  ): TypedContractMethod<[osloAmount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "sellOSLO"
  ): TypedContractMethod<
    [osloAmount: BigNumberish, minUSDTOut: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  filters: {};
}
