/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IRankSystemInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "claimRankBonus"
      | "getCurrentRank"
      | "getCurrentWeekId"
      | "getLegTurnover"
      | "getWeeklyTurnover"
      | "isRankQualified"
      | "receiveBonusPool"
      | "recordTurnover"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "claimRankBonus",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentRank",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentWeekId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getLegTurnover",
    values: [AddressLike, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getWeeklyTurnover",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isRankQualified",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "receiveBonusPool",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "recordTurnover",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "claimRankBonus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentRank",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentWeekId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLegTurnover",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getWeeklyTurnover",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isRankQualified",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "receiveBonusPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordTurnover",
    data: BytesLike
  ): Result;
}

export interface IRankSystem extends BaseContract {
  connect(runner?: ContractRunner | null): IRankSystem;
  waitForDeployment(): Promise<this>;

  interface: IRankSystemInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  claimRankBonus: TypedContractMethod<[], [void], "nonpayable">;

  getCurrentRank: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  getCurrentWeekId: TypedContractMethod<[], [bigint], "view">;

  getLegTurnover: TypedContractMethod<
    [user: AddressLike, weekId: BigNumberish, leg: AddressLike],
    [bigint],
    "view"
  >;

  getWeeklyTurnover: TypedContractMethod<
    [user: AddressLike, weekId: BigNumberish],
    [bigint],
    "view"
  >;

  isRankQualified: TypedContractMethod<[user: AddressLike], [boolean], "view">;

  receiveBonusPool: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  recordTurnover: TypedContractMethod<
    [user: AddressLike, leg: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "claimRankBonus"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getCurrentRank"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getCurrentWeekId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getLegTurnover"
  ): TypedContractMethod<
    [user: AddressLike, weekId: BigNumberish, leg: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getWeeklyTurnover"
  ): TypedContractMethod<
    [user: AddressLike, weekId: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "isRankQualified"
  ): TypedContractMethod<[user: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "receiveBonusPool"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "recordTurnover"
  ): TypedContractMethod<
    [user: AddressLike, leg: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  filters: {};
}
