/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IReferralInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "checkAndUnlockLevels"
      | "claimReferralRewards"
      | "distributeReferralCommission"
      | "getDirectReferrals"
      | "getQualifiedDirectsCount"
      | "getReferrer"
      | "getTeamSize"
      | "getUnlockedLevels"
      | "isRegistered"
      | "register"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "checkAndUnlockLevels",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claimReferralRewards",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "distributeReferralCommission",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDirectReferrals",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getQualifiedDirectsCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getReferrer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTeamSize",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUnlockedLevels",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isRegistered",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "register",
    values: [AddressLike, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "checkAndUnlockLevels",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimReferralRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "distributeReferralCommission",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDirectReferrals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getQualifiedDirectsCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReferrer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTeamSize",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUnlockedLevels",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isRegistered",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "register", data: BytesLike): Result;
}

export interface IReferral extends BaseContract {
  connect(runner?: ContractRunner | null): IReferral;
  waitForDeployment(): Promise<this>;

  interface: IReferralInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  checkAndUnlockLevels: TypedContractMethod<
    [user: AddressLike],
    [void],
    "nonpayable"
  >;

  claimReferralRewards: TypedContractMethod<[], [void], "nonpayable">;

  distributeReferralCommission: TypedContractMethod<
    [user: AddressLike, profitAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getDirectReferrals: TypedContractMethod<
    [user: AddressLike],
    [string[]],
    "view"
  >;

  getQualifiedDirectsCount: TypedContractMethod<
    [user: AddressLike],
    [bigint],
    "view"
  >;

  getReferrer: TypedContractMethod<[user: AddressLike], [string], "view">;

  getTeamSize: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  getUnlockedLevels: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  isRegistered: TypedContractMethod<[user: AddressLike], [boolean], "view">;

  register: TypedContractMethod<
    [user: AddressLike, referrer: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "checkAndUnlockLevels"
  ): TypedContractMethod<[user: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimReferralRewards"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "distributeReferralCommission"
  ): TypedContractMethod<
    [user: AddressLike, profitAmount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getDirectReferrals"
  ): TypedContractMethod<[user: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getQualifiedDirectsCount"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getReferrer"
  ): TypedContractMethod<[user: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getTeamSize"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUnlockedLevels"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "isRegistered"
  ): TypedContractMethod<[user: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "register"
  ): TypedContractMethod<
    [user: AddressLike, referrer: AddressLike],
    [void],
    "nonpayable"
  >;

  filters: {};
}
