/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IOSLOTokenV2Burn__factory } from "./IOSLOTokenV2Burn__factory";
export { OSLODexV2__factory } from "./OSLODexV2__factory";
