/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface OSLOConstantsInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BASIS_POINTS"
      | "CONTRACT_RESERVE"
      | "DAO_MONTHLY_ROYALTY_BP"
      | "DAO_TEAM_SIZE_REQUIREMENT"
      | "DEAD_ADDRESS"
      | "DEPOSIT_TO_COMPANY_BP"
      | "DEPOSIT_TO_DEX_BP"
      | "DEPOSIT_TO_PERFORMANCE_BP"
      | "DEPOSIT_TO_REWARD_BP"
      | "DEX_ALLOCATION"
      | "EARLY_EXIT_FEE_BP"
      | "EARLY_EXIT_PERIOD"
      | "INITIAL_DEX_OSLO"
      | "INITIAL_DEX_USDT"
      | "LAUNCH_TIMESTAMP"
      | "LIFETIME_RATE"
      | "LIFETIME_RATE_START"
      | "MAX_BURN_SUPPLY"
      | "MAX_DAO_MEMBERS"
      | "MAX_DEPOSIT_PER_TX"
      | "MAX_REFERRAL_LEVELS"
      | "MAX_TOTAL_DEPOSIT_PER_USER"
      | "MIN_REMAINING_SUPPLY"
      | "MIN_WITHDRAWAL_THRESHOLD"
      | "PKG1_FRI"
      | "PKG1_MIN"
      | "PKG1_MON"
      | "PKG1_SAT"
      | "PKG1_SUN"
      | "PKG1_THU"
      | "PKG1_TUE"
      | "PKG1_WED"
      | "PKG1_WEEKLY_TOTAL"
      | "PKG2_FRI"
      | "PKG2_MIN"
      | "PKG2_MON"
      | "PKG2_SAT"
      | "PKG2_SUN"
      | "PKG2_THU"
      | "PKG2_TUE"
      | "PKG2_WED"
      | "PKG2_WEEKLY_TOTAL"
      | "PROPOSAL_THRESHOLD_BP"
      | "QUALIFIED_DIRECT_MIN_DEPOSIT"
      | "RANK1_BONUS_BP"
      | "RANK1_TURNOVER"
      | "RANK2_BONUS_BP"
      | "RANK2_TURNOVER"
      | "RANK3_BONUS_BP"
      | "RANK3_TURNOVER"
      | "RANK4_BONUS_BP"
      | "RANK4_TURNOVER"
      | "RANK5_BONUS_BP"
      | "RANK5_TURNOVER"
      | "RANK6_BONUS_BP"
      | "RANK6_TURNOVER"
      | "RANK7_BONUS_BP"
      | "RANK7_TURNOVER"
      | "RANK_MAIN_LEG_MAX_BP"
      | "RANK_OTHER_LEGS_MIN_BP"
      | "REFERRAL_L11_20_BP"
      | "REFERRAL_L1_BP"
      | "REFERRAL_L2_BP"
      | "REFERRAL_L3_10_BP"
      | "RETURN_CAP_MULTIPLIER"
      | "SELL_BURN_BP"
      | "SELL_TAX_BP"
      | "SELL_TAX_FEE_BURN_BP"
      | "SELL_TAX_TO_BURN_BP"
      | "SELL_TAX_TO_CONTRACT_BP"
      | "SELL_TO_LIQUIDITY_BP"
      | "TIMELOCK_DELAY"
      | "TOTAL_SUPPLY"
      | "TREASURY_TO_DAO_BP"
      | "TREASURY_TO_LP_BP"
      | "TREASURY_TO_RANK_BP"
      | "VOTING_PERIOD_BLOCKS"
      | "WEEK_DURATION"
      | "WITHDRAWAL_FEE_BP"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "BASIS_POINTS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "CONTRACT_RESERVE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DAO_MONTHLY_ROYALTY_BP",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DAO_TEAM_SIZE_REQUIREMENT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEAD_ADDRESS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEPOSIT_TO_COMPANY_BP",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEPOSIT_TO_DEX_BP",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEPOSIT_TO_PERFORMANCE_BP",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEPOSIT_TO_REWARD_BP",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEX_ALLOCATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "EARLY_EXIT_FEE_BP",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "EARLY_EXIT_PERIOD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "INITIAL_DEX_OSLO",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "INITIAL_DEX_USDT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "LAUNCH_TIMESTAMP",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "LIFETIME_RATE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "LIFETIME_RATE_START",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_BURN_SUPPLY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_DAO_MEMBERS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_DEPOSIT_PER_TX",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_REFERRAL_LEVELS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_TOTAL_DEPOSIT_PER_USER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_REMAINING_SUPPLY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_WITHDRAWAL_THRESHOLD",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "PKG1_FRI", values?: undefined): string;
  encodeFunctionData(functionFragment: "PKG1_MIN", values?: undefined): string;
  encodeFunctionData(functionFragment: "PKG1_MON", values?: undefined): string;
  encodeFunctionData(functionFragment: "PKG1_SAT", values?: undefined): string;
  encodeFunctionData(functionFragment: "PKG1_SUN", values?: undefined): string;
  encodeFunctionData(functionFragment: "PKG1_THU", values?: undefined): string;
  encodeFunctionData(functionFragment: "PKG1_TUE", values?: undefined): string;
  encodeFunctionData(functionFragment: "PKG1_WED", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "PKG1_WEEKLY_TOTAL",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "PKG2_FRI", values?: undefined): string;
  encodeFunctionData(functionFragment: "PKG2_MIN", values?: undefined): string;
  encodeFunctionData(functionFragment: "PKG2_MON", values?: undefined): string;
  encodeFunctionData(functionFragment: "PKG2_SAT", values?: undefined): string;
  encodeFunctionData(functionFragment: "PKG2_SUN", values?: undefined): string;
  encodeFunctionData(functionFragment: "PKG2_THU", values?: undefined): string;
  encodeFunctionData(functionFragment: "PKG2_TUE", values?: undefined): string;
  encodeFunctionData(functionFragment: "PKG2_WED", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "PKG2_WEEKLY_TOTAL",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PROPOSAL_THRESHOLD_BP",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "QUALIFIED_DIRECT_MIN_DEPOSIT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "RANK1_BONUS_BP",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "RANK1_TURNOVER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "RANK2_BONUS_BP",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "RANK2_TURNOVER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "RANK3_BONUS_BP",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "RANK3_TURNOVER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "RANK4_BONUS_BP",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "RANK4_TURNOVER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "RANK5_BONUS_BP",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "RANK5_TURNOVER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "RANK6_BONUS_BP",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "RANK6_TURNOVER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "RANK7_BONUS_BP",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "RANK7_TURNOVER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "RANK_MAIN_LEG_MAX_BP",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "RANK_OTHER_LEGS_MIN_BP",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "REFERRAL_L11_20_BP",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "REFERRAL_L1_BP",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "REFERRAL_L2_BP",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "REFERRAL_L3_10_BP",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "RETURN_CAP_MULTIPLIER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SELL_BURN_BP",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SELL_TAX_BP",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SELL_TAX_FEE_BURN_BP",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SELL_TAX_TO_BURN_BP",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SELL_TAX_TO_CONTRACT_BP",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SELL_TO_LIQUIDITY_BP",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TIMELOCK_DELAY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TOTAL_SUPPLY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TREASURY_TO_DAO_BP",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TREASURY_TO_LP_BP",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TREASURY_TO_RANK_BP",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "VOTING_PERIOD_BLOCKS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "WEEK_DURATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "WITHDRAWAL_FEE_BP",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "BASIS_POINTS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "CONTRACT_RESERVE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DAO_MONTHLY_ROYALTY_BP",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DAO_TEAM_SIZE_REQUIREMENT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEAD_ADDRESS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEPOSIT_TO_COMPANY_BP",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEPOSIT_TO_DEX_BP",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEPOSIT_TO_PERFORMANCE_BP",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEPOSIT_TO_REWARD_BP",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEX_ALLOCATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "EARLY_EXIT_FEE_BP",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "EARLY_EXIT_PERIOD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "INITIAL_DEX_OSLO",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "INITIAL_DEX_USDT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "LAUNCH_TIMESTAMP",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "LIFETIME_RATE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "LIFETIME_RATE_START",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_BURN_SUPPLY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_DAO_MEMBERS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_DEPOSIT_PER_TX",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_REFERRAL_LEVELS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_TOTAL_DEPOSIT_PER_USER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_REMAINING_SUPPLY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_WITHDRAWAL_THRESHOLD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "PKG1_FRI", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "PKG1_MIN", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "PKG1_MON", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "PKG1_SAT", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "PKG1_SUN", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "PKG1_THU", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "PKG1_TUE", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "PKG1_WED", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "PKG1_WEEKLY_TOTAL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "PKG2_FRI", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "PKG2_MIN", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "PKG2_MON", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "PKG2_SAT", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "PKG2_SUN", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "PKG2_THU", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "PKG2_TUE", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "PKG2_WED", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "PKG2_WEEKLY_TOTAL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PROPOSAL_THRESHOLD_BP",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "QUALIFIED_DIRECT_MIN_DEPOSIT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "RANK1_BONUS_BP",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "RANK1_TURNOVER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "RANK2_BONUS_BP",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "RANK2_TURNOVER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "RANK3_BONUS_BP",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "RANK3_TURNOVER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "RANK4_BONUS_BP",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "RANK4_TURNOVER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "RANK5_BONUS_BP",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "RANK5_TURNOVER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "RANK6_BONUS_BP",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "RANK6_TURNOVER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "RANK7_BONUS_BP",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "RANK7_TURNOVER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "RANK_MAIN_LEG_MAX_BP",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "RANK_OTHER_LEGS_MIN_BP",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "REFERRAL_L11_20_BP",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "REFERRAL_L1_BP",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "REFERRAL_L2_BP",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "REFERRAL_L3_10_BP",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "RETURN_CAP_MULTIPLIER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SELL_BURN_BP",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SELL_TAX_BP",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SELL_TAX_FEE_BURN_BP",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SELL_TAX_TO_BURN_BP",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SELL_TAX_TO_CONTRACT_BP",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SELL_TO_LIQUIDITY_BP",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TIMELOCK_DELAY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TOTAL_SUPPLY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TREASURY_TO_DAO_BP",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TREASURY_TO_LP_BP",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TREASURY_TO_RANK_BP",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "VOTING_PERIOD_BLOCKS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "WEEK_DURATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "WITHDRAWAL_FEE_BP",
    data: BytesLike
  ): Result;
}

export interface OSLOConstants extends BaseContract {
  connect(runner?: ContractRunner | null): OSLOConstants;
  waitForDeployment(): Promise<this>;

  interface: OSLOConstantsInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BASIS_POINTS: TypedContractMethod<[], [bigint], "view">;

  CONTRACT_RESERVE: TypedContractMethod<[], [bigint], "view">;

  DAO_MONTHLY_ROYALTY_BP: TypedContractMethod<[], [bigint], "view">;

  DAO_TEAM_SIZE_REQUIREMENT: TypedContractMethod<[], [bigint], "view">;

  DEAD_ADDRESS: TypedContractMethod<[], [string], "view">;

  DEPOSIT_TO_COMPANY_BP: TypedContractMethod<[], [bigint], "view">;

  DEPOSIT_TO_DEX_BP: TypedContractMethod<[], [bigint], "view">;

  DEPOSIT_TO_PERFORMANCE_BP: TypedContractMethod<[], [bigint], "view">;

  DEPOSIT_TO_REWARD_BP: TypedContractMethod<[], [bigint], "view">;

  DEX_ALLOCATION: TypedContractMethod<[], [bigint], "view">;

  EARLY_EXIT_FEE_BP: TypedContractMethod<[], [bigint], "view">;

  EARLY_EXIT_PERIOD: TypedContractMethod<[], [bigint], "view">;

  INITIAL_DEX_OSLO: TypedContractMethod<[], [bigint], "view">;

  INITIAL_DEX_USDT: TypedContractMethod<[], [bigint], "view">;

  LAUNCH_TIMESTAMP: TypedContractMethod<[], [bigint], "view">;

  LIFETIME_RATE: TypedContractMethod<[], [bigint], "view">;

  LIFETIME_RATE_START: TypedContractMethod<[], [bigint], "view">;

  MAX_BURN_SUPPLY: TypedContractMethod<[], [bigint], "view">;

  MAX_DAO_MEMBERS: TypedContractMethod<[], [bigint], "view">;

  MAX_DEPOSIT_PER_TX: TypedContractMethod<[], [bigint], "view">;

  MAX_REFERRAL_LEVELS: TypedContractMethod<[], [bigint], "view">;

  MAX_TOTAL_DEPOSIT_PER_USER: TypedContractMethod<[], [bigint], "view">;

  MIN_REMAINING_SUPPLY: TypedContractMethod<[], [bigint], "view">;

  MIN_WITHDRAWAL_THRESHOLD: TypedContractMethod<[], [bigint], "view">;

  PKG1_FRI: TypedContractMethod<[], [bigint], "view">;

  PKG1_MIN: TypedContractMethod<[], [bigint], "view">;

  PKG1_MON: TypedContractMethod<[], [bigint], "view">;

  PKG1_SAT: TypedContractMethod<[], [bigint], "view">;

  PKG1_SUN: TypedContractMethod<[], [bigint], "view">;

  PKG1_THU: TypedContractMethod<[], [bigint], "view">;

  PKG1_TUE: TypedContractMethod<[], [bigint], "view">;

  PKG1_WED: TypedContractMethod<[], [bigint], "view">;

  PKG1_WEEKLY_TOTAL: TypedContractMethod<[], [bigint], "view">;

  PKG2_FRI: TypedContractMethod<[], [bigint], "view">;

  PKG2_MIN: TypedContractMethod<[], [bigint], "view">;

  PKG2_MON: TypedContractMethod<[], [bigint], "view">;

  PKG2_SAT: TypedContractMethod<[], [bigint], "view">;

  PKG2_SUN: TypedContractMethod<[], [bigint], "view">;

  PKG2_THU: TypedContractMethod<[], [bigint], "view">;

  PKG2_TUE: TypedContractMethod<[], [bigint], "view">;

  PKG2_WED: TypedContractMethod<[], [bigint], "view">;

  PKG2_WEEKLY_TOTAL: TypedContractMethod<[], [bigint], "view">;

  PROPOSAL_THRESHOLD_BP: TypedContractMethod<[], [bigint], "view">;

  QUALIFIED_DIRECT_MIN_DEPOSIT: TypedContractMethod<[], [bigint], "view">;

  RANK1_BONUS_BP: TypedContractMethod<[], [bigint], "view">;

  RANK1_TURNOVER: TypedContractMethod<[], [bigint], "view">;

  RANK2_BONUS_BP: TypedContractMethod<[], [bigint], "view">;

  RANK2_TURNOVER: TypedContractMethod<[], [bigint], "view">;

  RANK3_BONUS_BP: TypedContractMethod<[], [bigint], "view">;

  RANK3_TURNOVER: TypedContractMethod<[], [bigint], "view">;

  RANK4_BONUS_BP: TypedContractMethod<[], [bigint], "view">;

  RANK4_TURNOVER: TypedContractMethod<[], [bigint], "view">;

  RANK5_BONUS_BP: TypedContractMethod<[], [bigint], "view">;

  RANK5_TURNOVER: TypedContractMethod<[], [bigint], "view">;

  RANK6_BONUS_BP: TypedContractMethod<[], [bigint], "view">;

  RANK6_TURNOVER: TypedContractMethod<[], [bigint], "view">;

  RANK7_BONUS_BP: TypedContractMethod<[], [bigint], "view">;

  RANK7_TURNOVER: TypedContractMethod<[], [bigint], "view">;

  RANK_MAIN_LEG_MAX_BP: TypedContractMethod<[], [bigint], "view">;

  RANK_OTHER_LEGS_MIN_BP: TypedContractMethod<[], [bigint], "view">;

  REFERRAL_L11_20_BP: TypedContractMethod<[], [bigint], "view">;

  REFERRAL_L1_BP: TypedContractMethod<[], [bigint], "view">;

  REFERRAL_L2_BP: TypedContractMethod<[], [bigint], "view">;

  REFERRAL_L3_10_BP: TypedContractMethod<[], [bigint], "view">;

  RETURN_CAP_MULTIPLIER: TypedContractMethod<[], [bigint], "view">;

  SELL_BURN_BP: TypedContractMethod<[], [bigint], "view">;

  SELL_TAX_BP: TypedContractMethod<[], [bigint], "view">;

  SELL_TAX_FEE_BURN_BP: TypedContractMethod<[], [bigint], "view">;

  SELL_TAX_TO_BURN_BP: TypedContractMethod<[], [bigint], "view">;

  SELL_TAX_TO_CONTRACT_BP: TypedContractMethod<[], [bigint], "view">;

  SELL_TO_LIQUIDITY_BP: TypedContractMethod<[], [bigint], "view">;

  TIMELOCK_DELAY: TypedContractMethod<[], [bigint], "view">;

  TOTAL_SUPPLY: TypedContractMethod<[], [bigint], "view">;

  TREASURY_TO_DAO_BP: TypedContractMethod<[], [bigint], "view">;

  TREASURY_TO_LP_BP: TypedContractMethod<[], [bigint], "view">;

  TREASURY_TO_RANK_BP: TypedContractMethod<[], [bigint], "view">;

  VOTING_PERIOD_BLOCKS: TypedContractMethod<[], [bigint], "view">;

  WEEK_DURATION: TypedContractMethod<[], [bigint], "view">;

  WITHDRAWAL_FEE_BP: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BASIS_POINTS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "CONTRACT_RESERVE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "DAO_MONTHLY_ROYALTY_BP"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "DAO_TEAM_SIZE_REQUIREMENT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "DEAD_ADDRESS"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DEPOSIT_TO_COMPANY_BP"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "DEPOSIT_TO_DEX_BP"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "DEPOSIT_TO_PERFORMANCE_BP"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "DEPOSIT_TO_REWARD_BP"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "DEX_ALLOCATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "EARLY_EXIT_FEE_BP"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "EARLY_EXIT_PERIOD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "INITIAL_DEX_OSLO"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "INITIAL_DEX_USDT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "LAUNCH_TIMESTAMP"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "LIFETIME_RATE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "LIFETIME_RATE_START"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_BURN_SUPPLY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_DAO_MEMBERS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_DEPOSIT_PER_TX"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_REFERRAL_LEVELS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_TOTAL_DEPOSIT_PER_USER"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_REMAINING_SUPPLY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_WITHDRAWAL_THRESHOLD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PKG1_FRI"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PKG1_MIN"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PKG1_MON"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PKG1_SAT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PKG1_SUN"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PKG1_THU"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PKG1_TUE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PKG1_WED"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PKG1_WEEKLY_TOTAL"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PKG2_FRI"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PKG2_MIN"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PKG2_MON"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PKG2_SAT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PKG2_SUN"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PKG2_THU"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PKG2_TUE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PKG2_WED"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PKG2_WEEKLY_TOTAL"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PROPOSAL_THRESHOLD_BP"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "QUALIFIED_DIRECT_MIN_DEPOSIT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "RANK1_BONUS_BP"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "RANK1_TURNOVER"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "RANK2_BONUS_BP"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "RANK2_TURNOVER"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "RANK3_BONUS_BP"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "RANK3_TURNOVER"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "RANK4_BONUS_BP"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "RANK4_TURNOVER"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "RANK5_BONUS_BP"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "RANK5_TURNOVER"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "RANK6_BONUS_BP"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "RANK6_TURNOVER"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "RANK7_BONUS_BP"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "RANK7_TURNOVER"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "RANK_MAIN_LEG_MAX_BP"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "RANK_OTHER_LEGS_MIN_BP"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "REFERRAL_L11_20_BP"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "REFERRAL_L1_BP"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "REFERRAL_L2_BP"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "REFERRAL_L3_10_BP"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "RETURN_CAP_MULTIPLIER"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SELL_BURN_BP"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SELL_TAX_BP"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SELL_TAX_FEE_BURN_BP"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SELL_TAX_TO_BURN_BP"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SELL_TAX_TO_CONTRACT_BP"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SELL_TO_LIQUIDITY_BP"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TIMELOCK_DELAY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TOTAL_SUPPLY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TREASURY_TO_DAO_BP"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TREASURY_TO_LP_BP"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TREASURY_TO_RANK_BP"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "VOTING_PERIOD_BLOCKS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "WEEK_DURATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "WITHDRAWAL_FEE_BP"
  ): TypedContractMethod<[], [bigint], "view">;

  filters: {};
}
